data:
    frame_files:
        H1: "/home/angel/Documents/pycbc_checks/H-H1_GWOSC_4KHZ_R1-1185387760-4096.gwf"
        L1: "/home/angel/Documents/pycbc_checks/L-L1_GWOSC_4KHZ_R1-1185387760-4096.gwf"
        H1_lensed: "/home/angel/Documents/pycbc_checks/H-H1_GWOSC_O2_4KHZ_R1-1185435648-4096.gwf"
        L1_lensed: "/home/angel/Documents/pycbc_checks/L-L1_GWOSC_O2_4KHZ_R1-1185435648-4096.gwf" 
    channels:
        H1: "H1:GWOSC-4KHZ_R1_STRAIN"
        L1: "L1:GWOSC-4KHZ_R1_STRAIN"
        H1_lensed: "H1:GWOSC-4KHZ_R1_STRAIN"
        L1_lensed: "L1:GWOSC-4KHZ_R1_STRAIN" 
    posteriors_file: "../../Documents/pycbc_checks/IGWN-GWTC2p1-v2-GW170729_185629_PEDataRelease_mixed_cosmo.h5"

injection:
    time_gps_past_seconds: 1185389807.298705
    time_gps_future_seconds: 1185437144.7875977
    sample_rate: 4096.0
    unlensed_instruments: ["H1", "L1"]
    lensed_instruments: ["H1", "L1"]
    segment_length_seconds: 256
    slide_shift_seconds: 1
    low_frequency_cutoff: 30.0
    reference_frequency: 50.0
    sngl_snr_threshold: 0.0
    downsample_factor: 1
    upsample_threshold: 0.0
    upsample_method: "pruned_fft"
    order: -1
    taper_template: 
    approximant: "IMRPhenomXAS"
    coinc_threshold: 0.0
    do_null_cut: False
    null_min: 5.25
    null_grad: 0.2
    null_step: 20.0
    cluster_window: 0.1
    pad_seconds: 8
    segment_start_pad_seconds: 111
    segment_end_pad_seconds: 17

chisq:
    chisq_bins: "0.9*get_freq('fSEOBNRv4Peak',params.mass1,params.mass2,params.spin1z,params.spin2z)**(2./3.)"
    autochi_stride: 0
    autochi_number_points: 0
    autochi_onesided: 
    autochi_two_phase: False
    autochi_reverse_template: False
    autochi_max_valued: False
    autochi_max_valued_dof: 
    chisq_index: 6.0
    chisq_nhigh: 2.0

psd:
    psd_segment_stride_seconds: 8.0
    psd_segment_length_seconds: 32.0
    psd_num_segments: 29
    strain_high_pass_hertz: 25.0
    psd_estimation: "median"

sky_patch:
    angular_spacing: 1.8
    sky_error: 0.1 

output:
    output_file_name: "results.json"

injection_parameters:
    mass_1: 79.45
    mass_2: 48.5
    a_1: 0.6
    a_2: 0.05
    tilt_1: 0.0
    tilt_2: 0.0
    phi_12: 0.0
    phi_jl: 0.0
    luminosity_distance: 2000.0
    theta_jn: 1.3
    psi: 0.5
    phase: 0.1
    geocent_time: 1185389807.298705
    ra: 6.0
    dec: -1.2
